title: MOLGENIS
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  MOLGENIS open source project website.
layout: green #default layout
baseurl:
url: https://www.molgenis.org

# Build settings
markdown: kramdown
plugins:
  - addressable
  - jekyll-feed
  - jekyll-target-blank
exclude:
  - Gemfile
  - Gemfile.lock
